### ISSUE TITLE
Interrupting kernel build with Ctrl+C hangs the terminal

### ISSUE THREAD

**Issue by xairy** [a13xp0p0v/kernel-build-containers#1]
Can be resolved manually with sending a `kill -9` to the `make` process.

**Comment by a13xp0p0v** [comment]
Hi @xairy,
I'm glad that you use this tool!
Thanks for the report.

That was a tricky bug: 
`subprocess.Popen()` starts `docker run` with `-it` arguments.
That makes docker run in interactive mode, but breaks the delivery of
`KeyboardInterrupt` in python. So `Ctrl+C` sometimes doesn't work properly.

I added a new `-n` argument for `run_container.sh` to disable docker interactive mode
when needed. I see that the issue is fixed. Can you reproduce it?

**Comment by xairy** [comment]
Hi Alex,

Now Ctrl+C works, thanks for the fix and for the tool!
